spring.application.name=ApiGateway

server.port=${API_GATEWAY_PORT}

#/products/* -> productService
spring.cloud.gateway.routes[0].id=productService
spring.cloud.gateway.routes[0].predicates[0]=Path=/product/**
spring.cloud.gateway.routes[0].uri=lb://PRODUCTSERVICE

#/users/* -> userService
spring.cloud.gateway.routes[1].id=userService
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**
spring.cloud.gateway.routes[1].uri=lb://USERSERVICE

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true
